global.demo_build = 0;
randomize();
storyline_vars();
global.gamepad_connected = 0;
global.up_key = 0;
global.left_key = 0;
global.down_key = 0;
global.right_key = 0;
global.up_key_pressed = 0;
global.left_key_pressed = 0;
global.down_key_pressed = 0;
global.right_key_pressed = 0;
global.a_key = 0;
global.b_key = 0;
global.x_key = 0;
global.y_key = 0;
global.accept_key = 0;
global.cancel_key = 0;
global.event_key = 0;
global.player_speed_cur = 2;
global.player_speed_nrm = 2;
global.player_clothing = "pajama";
global.player_frozen = 0;
global.player_combat = 0;
global.player_direction = 3;
global.player_moving = 0;
global.shaders_active = 0;

if (shader_is_compiled(shd_grayscale))
    global.shaders_active = 1;

global.surface_offset_x = 0;
global.surface_offset_y = 0;
global.shadow_surface = -4;
global.arena_surface = -4;
global.world_seed = string(random_get_seed());
global.start_room = 13;
global.world_music = 0;
global.start_x = 0;
global.start_y = 0;
global.save_file_name = "heartbound_save4.thor";
global.menu_active = 0;
global.current_menu = 0;
global.cursor_active = 1;
global.cursor_model = 1152;
global.combat_active = 0;
global.player_hp_cur = 10;
global.player_hp_max = 10;
global.enemy_hp_cur = 0;
global.enemy_hp_max = 0;
global.enemy_hp_check = 0;
global.base_message = "";
global.message_language_list = 0;
global.message_speed_list = 0;
global.message_voice_list = 0;
global.message_emotion_list = 0;
global.message_color_list = 0;
global.message_spinning_list = 0;
global.message_text = "";
global.altmessage_text = "";
global.conv_talking = 0;
global.text_complete = 0;
global.current_talker = 0;
global.game_language = "english";
global.language_known = 0;
global.language_map = 0;
dialog_talky_init();
dialog_voice_init();
letter_map_init();
glyph_map_init();
